global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 2m

receivers:
  - name: 'telegram'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: <BotToken>
        chat_id: <chatID>
        message: '{{ .CommonAnnotations.summary }}{{ .CommonAnnotations.description }}'
        parse_mode: 'HTML'
        send_resolved: true
        disable_notifications: false
        http_config:
          bearer_token: <BotToken>
