global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'python_script'
    static_configs:
      - targets: ['localhost:8000']

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'localhost:9093'  # Address of your Alertmanager instance

rule_files:
  - "alert_rules.yml"  # Path to your alerting rules file



